### ISSUE TITLE
Servo is killing the Cat

### ISSUE THREAD

**Issue by pythoneer** [ruplace-controllers/ruplace-target#1]
In the current version isn't the Servo logo destroying the cat logo kibwen was so worried by even touching the "B" ... i imagine it got totally destroyed with this design – no?  

Let alone the fact, that multiple versions of the bot start to fight against their "current" version of the design – (especially the Redox one)  i'll guess its to late to change anything, isn't it?

**Comment by Diggsey** [comment]
Already fixed. Old versions of the bot will stop working because I broke the JSON for them.

**Comment by Diggsey** [comment]
Also the servo text is removed

**Comment by pythoneer** [comment]
Genius!
