### ISSUE TITLE
new conflict with concentric squares

### ISSUE THREAD

**Issue by tspiteri** [ruplace-controllers/ruplace-target#2]
Increasing the used space by one pixel up in the REDOX OS bit is going to land us into a new conflict with the relocated concentric squares. Their new upper black outline is forming at y=623, so probably they intend to have a bottom black outline at y=633. We should really leave this space to them.

**Comment by Diggsey** [comment]
I've moved it down 1 pixel.

**Comment by tspiteri** [comment]
Sorry to pester @Diggsey, but the file the bot is using (https://raw.githubusercontent.com/ruplace-controllers/ruplace-target/d4310ce13db9171d8b79e867fdd9ccc534aa67f4/ruplace.png) is still not updated.

**Comment by Diggsey** [comment]
Oops, fixed, thanks.

**Comment by tspiteri** [comment]
Thank you.
