### ISSUE TITLE
Image URL

### ISSUE THREAD

**Issue by EpicatSupercell** [ruplace-controllers/ruplace-target#3]
Souldn't the URL be
`https://raw.githubusercontent.com/ruplace-controllers/ruplace-target/master/ruplace.png`
so that it always is the most updated version, instead of pinning on a specific commit?

**Comment by Diggsey** [comment]
No, pinning to a commit ensure that the JSON always matches the image, regardless of any caching behaviour (github heavily caches from their CDN).

**Comment by Diggsey** [comment]
It also means the program can use the image URL to determine if it needs to update.
